apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-side
spec:
  replicas: 1
  selector:
    matchLabels:
      side: cloud
  template:
    metadata:
      labels:
        side: cloud
    spec:
      containers:
      - name: cloud
        imagePullPolicy: Always
        image: turbogoosen/cloud:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-port
        - name: POSTGRES_DBNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-dbname
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-service
spec:
  selector:
    side: cloud
  ports:
  - port: 8000
    targetPort: 8000