apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: "base64-encoded db user here"
  postgres-password: "base64-encoded db password here"
  postgres-host: "base64-encoded db host here"